# Generated by Django 4.2 on 2023-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='account_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='bg_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_type',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='custom_author_names',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='custom_contents_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_tasks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
