# Generated by Django 4.2 on 2023-04-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_course_authors_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='course',
            name='types',
        ),
    ]
